{
 "title": "Realtime Crypto Dashboard",
 "time": { "from": "2026-01-02T12:10:00.000Z", "to": "2026-01-02T14:03:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "symbol",
    "query": "SELECT DISTINCT symbol FROM crypto_prices;"
   },
   {
    "name": "timeframe",
    "query": "candle_1m,candle_5m,candle_15m,candle_45m,candle_1h"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n  <h1>CRYPTO REAL-TIME DASHBOARD</h1>\n  <hr>\n  <h2>Monitoring koin: <strong>$symbol</strong></h2>\n  <hr>\n</div>"
   }
  },
  {
   "title": "$symbol Prices",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "crypto-stream-sink",
     "rawSql": "select price,event_time as time from crypto_prices WHERE symbol = '$symbol' order by time asc;"
    }
   ]
  },
  {
   "title": "candle_1m",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 4 },
   "targets": [
    {
     "dataset": "crypto-stream-sink",
     "rawSql": "SELECT\r\n  -- Kurangi 7 jam dari kolom waktu agar sinkron dengan jam lokal/raw data\r\n  (time - INTERVAL '7 hours') AS \"time\",\r\n  open,\r\n  high,\r\n  low,\r\n  close\r\nFROM $timeframe\r\nWHERE symbol = '$symbol'\r\n  -- Filter waktu juga harus digeser agar Grafana mencari di range yang tepat\r\n  AND time BETWEEN ($__timeFrom()::timestamp + INTERVAL '7 hours') \r\n               AND ($__timeTo()::timestamp + INTERVAL '7 hours')\r\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Last Price for $symbol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crypto-stream-sink",
     "rawSql": "SELECT \r\n  event_time AS \"time\",\r\n  price AS \"Last Price\",\r\n  symbol\r\nFROM crypto_prices \r\nWHERE symbol = '$symbol'\r\nORDER BY time DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crypto-stream-sink",
     "rawSql": "WITH price_data AS (\r\n    SELECT close \r\n    FROM window_1m \r\n    WHERE symbol = '$symbol' \r\n    ORDER BY window_start DESC LIMIT 1\r\n),\r\nfirst_price AS (\r\n    SELECT close \r\n    FROM window_1m \r\n    WHERE symbol = '$symbol' \r\n    ORDER BY window_start ASC LIMIT 1\r\n)\r\nSELECT \r\n    ((p.close - f.close) / f.close) * 100 AS \"Change %\"\r\nFROM price_data p, first_price f"
    }
   ]
  }
 ]
}